services:
  turtlebot3:
    build:
      context: .
      dockerfile: Dockerfile
    image: turtlebot3_drlnav:latest
    container_name: turtlebot3_drlnav

    working_dir: /home/turtlebot3_drlnav

    stdin_open: true
    tty: true

    network_mode: host
    ipc: host

    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority

      - ROS_DOMAIN_ID=1

      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      - LIBGL_ALWAYS_SOFTWARE=0
      - MESA_GL_VERSION_OVERRIDE=3.3

    devices:
      - /dev/dri:/dev/dri

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro

      - ./turtlebot3_drlnav:/home/turtlebot3_drlnav

    # NVIDIA GPU passthrough
    #     Remove this entire 'deploy' block if you have no NVIDIA GPU.


  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - graphics
                - compute
                - utility

    restart: unless-stopped